src/Entity/Fournisseurs.php
<?php

namespace App\Entity;

use App\Repository\FournisseursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: FournisseursRepository::class)]
#[Broadcast]
class Fournisseurs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column (name: 'Id_fournisseur')]
    private ?int $Id_fournisseur = null;

    #[ORM\Column(length: 50)]
    private ?string $Code_fournisseur = null;

    #[ORM\Column(length: 50)]
    private ?string $Raison_sociale = null;

    #[ORM\Column(length: 50)]
    private ?string $Rue_fournisseur = null;

    #[ORM\Column(length: 50)]
    private ?string $Code_postal = null;

    #[ORM\Column(length: 50)]
    private ?string $Localite = null;

    #[ORM\Column(length: 50)]
    private ?string $Pays = null;

    #[ORM\Column(length: 50)]
    private ?string $Tel_fournisseur = null;

    #[ORM\Column(length: 50)]
    private ?string $Url_fournisseur = null;

    #[ORM\Column(length: 50)]
    private ?string $Email_fournisseur = null;

    #[ORM\Column(length: 50)]
    private ?string $Fax_fournisseur = null;

    #[ORM\OneToMany(targetEntity: Commander::class, mappedBy: 'Id_fournisseur')]
    private Collection $commanders;

    public function __construct()
    {
        $this->commanders = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->Id_fournisseur;
    }

    public function getCodeFournisseur(): ?string
    {
        return $this->Code_fournisseur;
    }

    public function setCodeFournisseur(string $Code_fournisseur): static
    {
        $this->Code_fournisseur = $Code_fournisseur;

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->Raison_sociale;
    }

    public function setRaisonSociale(string $Raison_sociale): static
    {
        $this->Raison_sociale = $Raison_sociale;

        return $this;
    }

    public function getRueFournisseur(): ?string
    {
        return $this->Rue_fournisseur;
    }

    public function setRueFournisseur(string $Rue_fournisseur): static
    {
        $this->Rue_fournisseur = $Rue_fournisseur;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->Code_postal;
    }

    public function setCodePostal(string $Code_postal): static
    {
        $this->Code_postal = $Code_postal;

        return $this;
    }

    public function getLocalite(): ?string
    {
        return $this->Localite;
    }

    public function setLocalite(string $Localite): static
    {
        $this->Localite = $Localite;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): static
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getTelFournisseur(): ?string
    {
        return $this->Tel_fournisseur;
    }

    public function setTelFournisseur(string $Tel_fournisseur): static
    {
        $this->Tel_fournisseur = $Tel_fournisseur;

        return $this;
    }

    public function getUrlFournisseur(): ?string
    {
        return $this->Url_fournisseur;
    }

    public function setUrlFournisseur(string $Url_fournisseur): static
    {
        $this->Url_fournisseur = $Url_fournisseur;

        return $this;
    }

    public function getEmailFournisseur(): ?string
    {
        return $this->Email_fournisseur;
    }

    public function setEmailFournisseur(string $Email_fournisseur): static
    {
        $this->Email_fournisseur = $Email_fournisseur;

        return $this;
    }

    public function getFaxFournisseur(): ?string
    {
        return $this->Fax_fournisseur;
    }

    public function setFaxFournisseur(string $Fax_fournisseur): static
    {
        $this->Fax_fournisseur = $Fax_fournisseur;

        return $this;
    }

    /**
     * @return Collection<int, Commander>
     */
    public function getCommanders(): Collection
    {
        return $this->commanders;
    }

    public function addCommander(Commander $commander): static
    {
        if (!$this->commanders->contains($commander)) {
            $this->commanders->add($commander);
            $commander->setIdFournisseur($this);
        }

        return $this;
    }

    public function removeCommander(Commander $commander): static
    {
        if ($this->commanders->removeElement($commander)) {
            // set the owning side to null (unless already changed)
            if ($commander->getIdFournisseur() === $this) {
                $commander->setIdFournisseur(null);
            }
        }

        return $this;
    }

    

    

   
}

src/Form/FournisseurType.php
<?php

namespace App\Form;

use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Fournisseurs;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FournisseurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Code_fournisseur')
            ->add('Raison_sociale')
            ->add('Rue_fournisseur')
            ->add('Code_postal')
            ->add('Localite')
            ->add('Pays')
            ->add('Tel_fournisseur')
            ->add('Url_fournisseur')
            ->add('Email_fournisseur')
            ->add('Fax_fournisseur');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Fournisseurs::class,
        ]);
    }
}

src/Controller/FournisseursController.php
<?php

namespace App\Controller;

use App\Form\RaisonSocialeType;
use App\Form\LocaliteType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Fournisseurs;
use App\Form\FournisseurType;
use App\Form\PaysType;
use App\Repository\FournisseursRepository;
// use App\Form\FournisseurType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FournisseursController extends AbstractController
{
    // AFFICHAGE TOUT LES FOURNISSEURS *************************************************************************************************************************************


    #[Route('/fournisseurs', name: 'app_fournisseurs', methods: ['GET'])]
    public function index(FournisseursRepository $fournisseursRepository): Response
    {

        return $this->render('fournisseurs/index.html.twig', [
            'fournisseurs' => $fournisseursRepository->findAll(),

        ]);
    }


    // AFFICHAGE FORMULAIRE POUR MODFICATION ***************************************************************************************************************


    #[Route('/fournisseurs/{id}/update', name: 'form_fournisseurs', methods: ['GET', 'POST'])]
    public function update(int $id, Request $request, FournisseursRepository  $fournisseursRepository, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FournisseurType::class, $fournisseursRepository->find($id));
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute(
                'app_fournisseurs',
                [],
                Response::HTTP_SEE_OTHER
            );
            
        }
        return $this->render('fournisseurs/update.html.twig', [
            'form' => $form, 'fournisseurs' => $fournisseursRepository->findAll(),

        ]);
    }

    // SUPPRIMER ***************************************************************************************************************


    #[Route('/fournisseurs/{id}/delete', name: 'delete_fournisseurs')]
    public function delete(int $id, EntityManagerInterface $entityManager,  FournisseursRepository $fournisseursRepository): Response
    {
        $fournisseurs = $fournisseursRepository->find($id);
        var_dump($fournisseurs);
        $entityManager->remove($fournisseurs);

        $entityManager->flush();
        return $this->redirectToRoute('app_fournisseurs');
    }

     // AJOUT ***************************************************************************************************************

     #[Route('/fournisseurs/create', name: 'create_fournisseurs', methods:['GET', 'POST'])]
     public function create_fournisseurs(Request $request, EntityManagerInterface $entityManager,  FournisseursRepository $fournisseursRepository ): Response
     {
 
         $fourniseurs = new Fournisseurs();
         $form = $this->createForm(FournisseurType::class, $fourniseurs);
         $form->handleRequest($request);
 
       if ($form->isSubmitted() && $form->isValid())
             {
             $entityManager->persist($fourniseurs); // persist fait le liens entre l'ORM et Symfony
             $entityManager->flush();              //flush fait le liens et applique les changements à la base de donnée
             return $this->redirectToRoute('app_fournisseurs', [], Response::HTTP_SEE_OTHER);  // Redirigez l'utilisateur vers une autre page, par exemple la liste des fournisseurs
             }
    
         return $this->render('fournisseurs/create.html.twig', [
             'form' => $form->createView()
         ]);
     }

    //   PAR RAISON SOCIALE *******************************************************************************************************

    #[Route('/Raison_sociale', name: 'forme_fournisseurs_raison_sociale', methods: [
        'GET',
        'POST'
    ])]
    public function forme_fournisseurs_raison_sociale(Request $request, FournisseursRepository $fournisseursRepo, EntityManagerInterface
    $entityManager)
    {

        $form = $this->createForm(RaisonSocialeType::class, null);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $raisonSocialeSelectionne = $form->get('Raison_sociale')->getData();

            
            return $this->render('fournisseurs/index.html.twig', [

                'fournisseurs' => $fournisseursRepo->findBy(['Raison_sociale' => $raisonSocialeSelectionne]),
            ]);
        }
        return $this->render('fournisseurs/form_raison_sociale.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    
    //   PAR LOCALITE *******************************************************************************************************

    #[Route('/localite', name: 'forme_fournisseurs_localite', methods: [
        'GET',
        'POST'
    ])]
    public function forme_fournisseurs_Localite(Request $request, FournisseursRepository $fournisseursRepo, EntityManagerInterface
    $entityManager)
    {

        $form = $this->createForm(LocaliteType::class, null);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $LocaliteSelectionne = $form->get('Localite')->getData();

            
            return $this->render('fournisseurs/index.html.twig', [

                'fournisseurs' => $fournisseursRepo->findBy(['Localite' => $LocaliteSelectionne]),
            ]);
        }
        return $this->render('fournisseurs/form_localite.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    //   PAR PAYS *******************************************************************************************************

    #[Route('/pays', name: 'forme_fournisseurs_pays', methods: [
        'GET',
        'POST'
    ])]
    public function forme_fournisseurs_pays(Request $request, FournisseursRepository $fournisseursRepo, EntityManagerInterface
    $entityManager)
    {

        $form = $this->createForm(PaysType::class, null);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $PaysSelectionne = $form->get('Pays')->getData();

            
            return $this->render('fournisseurs/index.html.twig', [

                'fournisseurs' => $fournisseursRepo->findBy(['Pays' => $PaysSelectionne]),
            ]);
        }
        return $this->render('fournisseurs/form_pays.html.twig', [
            'form' => $form->createView(),
        ]);
    }

     
}

templates/fournisseurs/create.html.twig
{% extends 'base.html.twig' %}

    {% block body %}
     <div class="text-center">
     <h1> Création d'un fournisseur </h1>

    {{ form_start(form) }}
        <div class ="mx-auto container  ml-5">
    {{ form_widget(form) }}

    <button type="submit" class="btn btn-primary  mt-4">{{ 'Validez la création' }}</button>
    </div>

    {{ form_end(form) }}
    </div>

{% endblock %}

templates/fournisseurs/form_localite.html.twig
{% block body %}
	{{ form_start(form) }}

	<button type="submit" name="save_button" class="btn btn-primary">Valider</button>
	{{ form_end(form) }}

{% endblock %}

templates/fournisseurs/form_pays.html.twig
{% block body %}
	{{ form_start(form) }}

	<button type="submit" name="save_button" class="btn btn-primary">Valider</button>
	{{ form_end(form) }}

{% endblock %}

templates/fournisseurs/form_raison_sociale.html.twig
{% block body %}
	{{ form_start(form) }}

	<button type="submit" name="save_button" class="btn btn-primary">Valider</button>
	{{ form_end(form) }}

{% endblock %}

templates/fournisseurs/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}
	<h1 class="text-center">
		Liste des fournisseurs
	</h1>
	<a class="btn btn-outline-secondary" href="{{ path('create_fournisseurs') }}" onclick="return confirm('Vous étes sur de vouloir ajouter un fournisseur?')">Ajout</a>

	<table class="example-wrapper table table-success table-striped">
		<tr>

			<TH>Code fournisseur</TH>
			<TH>Raison sociale</TH>
			<TH>Rue fournisseur</TH>
			<TH>Code postal</TH>
			<TH>Localité</TH>
			<TH>Pays</TH>
			<TH>Tel fournisseur</TH>
			<TH>Url fournisseur</TH>
			<TH>Email fournisseur</TH>
			<TH>Fax fournisseur</TH>
			<TH>Actions</TH>
		</tr>

		{% for fournisseur in fournisseurs %}
			<tr>
				<td>{{ fournisseur.codeFournisseur }}</td>
				<td>{{ fournisseur.raisonSociale }}</td>
				<td>{{ fournisseur.rueFournisseur }}</td>
				<td>{{ fournisseur.codePostal }}</td>
				<td>{{ fournisseur.localite }}</td>
				<td>{{ fournisseur.pays }}</td>
				<td>{{ fournisseur.telFournisseur }}</td>
				<td>{{ fournisseur.urlFournisseur }}</td>
				<td>{{ fournisseur.emailFournisseur }}</td>
				<td>{{ fournisseur.faxFournisseur }}</td>
				<td>

					<div class="container d-flex flex-raw">
						<a class="btn btn-outline-info" href="{{ path('form_fournisseurs', {'id': fournisseur.id}) }}" onclick=" return confirm('vous étes sur de vouloir modifer vos données?')">Modifier</a>


						<a class="btn btn-outline-danger" href="{{ path ('delete_fournisseurs', {'id':fournisseur.id}) }}" onclick="return confirm('Vous étes sur ? Vos données seront perdus.')">Supprimer</a>


					</div>


				</td>
			</tr>
		{% endfor %}

	</a>
</table>{% endblock %}

templates/fournisseurs/update.html.twig
{% extends 'base.html.twig' %}

    {% block title %}
        modification fournisseur
    {% endblock %}

    {% block body %}
     <div class="text-center">
     <h1> modification fournisseur </h1>

    {{ form_start(form) }}
        <div class ="mx-auto container  ml-5">
    {{ form_widget(form) }}

    <button type="submit" class="btn btn-primary  mt-4">{{ 'Validez la modification' }}</button>
    </div>

    {{ form_end(form) }}
    </div>

{% endblock %}